import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  clients: [
    {
      prenom: "Charles",
      nom: "Dupont",
      borne: 2,
      devis: null,
      etape: 1,
      contact: {
        adresse: "Place de la Bourse, 33000 Bordeaux",
        codePostal: 33400,
        tel: "01 23 45 67 89",
        email: "charles.dupont@gmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "David",
      nom: "Dubois",
      borne: 2,
      devis: null,
      etape: 2,
      contact: {
        adresse: "10 Allées des Tilleuls, 33000 Bordeaux",
        codePostal: 33400,
        tel: "01 23 45 67 89",
        email: "david.dubois@hotmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Marie",
      nom: "Carton",
      borne: 2,
      devis: null,
      etape: 3,
      contact: {
        adresse: "2 cité Verte, 33000 Bordeaux",
        codePostal: 33000,
        tel: "01 23 45 67 89",
        email: "marie.carton@orange.fr",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "José",
      nom: "Rae",
      borne: 2,
      devis: null,
      etape: 4,
      contact: {
        adresse: "152 Bd du Thé, 33400 Bordeaux",
        codePostal: 33400,
        tel: "01 23 45 67 89",
        email: "jose.r@gmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Vincent",
      nom: "Garcia",
      borne: 2,
      devis: null,
      etape: 1,
      contact: {
        adresse: "23 Bd des Prunes, 33000 Bordeaux",
        codePostal: 33000,
        tel: "01 23 45 67 89",
        email: "vince.garcia@bing.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Davide",
      nom: "Bois",
      borne: 2,
      devis: null,
      etape: 2,
      contact: {
        adresse: "20 rue Bilot, 33400 Bordeaux",
        codePostal: 33400,
        tel: "01 23 45 67 89",
        email: "davide.bois@gmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Maria",
      nom: "Cartani",
      borne: 2,
      devis: null,
      etape: 3,
      contact: {
        adresse: "4 rue Mesmer, 33000 Bordeaux",
        codePostal: 33000,
        tel: "01 23 45 67 89",
        email: "maria.cartani@hotmail.fr",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Joséphine",
      nom: "Rallet",
      borne: 2,
      devis: null,
      etape: 4,
      contact: {
        adresse: "Place de la Bourse, 33000 Bordeaux",
        codePostal: 33000,
        tel: "01 23 45 67 89",
        email: "Jose.phine@gmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Carlos",
      nom: "Ponte",
      borne: 2,
      devis: null,
      etape: 1,
      contact: {
        adresse: "8 Place de la Lune, 33200 Bordeaux",
        codePostal: 33200,
        tel: "01 23 45 67 89",
        email: "carlos.ponte@yahoo.fr",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Dave",
      nom: "Charrière",
      borne: 2,
      devis: null,
      etape: 2,
      contact: {
        adresse: "Place de la Bourse, 33400 Bordeaux",
        codePostal: 33400,
        tel: "01 23 45 67 89",
        email: "charriere.d@bordeaux.fr",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Jeanne",
      nom: "Aton",
      borne: 2,
      devis: null,
      etape: 3,
      contact: {
        adresse: "Place de la Bourse, 33000 Bordeaux",
        codePostal: 33000,
        tel: "01 23 45 67 89",
        email: "jeanne.aton@gmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Osias",
      nom: "Vallée",
      borne: 2,
      devis: null,
      etape: 4,
      contact: {
        adresse: "18 rue Sévran, 33100 Bordeaux",
        codePostal: 33100,
        tel: "01 23 45 67 89",
        email: "osias.val@hotmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Greg",
      nom: "Bollet",
      borne: 2,
      devis: null,
      etape: 1,
      contact: {
        adresse: "Place de la Bourse, 33000 Bordeaux",
        codePostal: 33000,
        tel: "01 23 45 67 89",
        email: "greg.bollet@yahoo.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Phil",
      nom: "Barnum",
      borne: 2,
      devis: null,
      etape: 2,
      contact: {
        adresse: "Place des Victoires, 33200 Bordeaux",
        codePostal: 33200,
        tel: "01 23 45 67 89",
        email: "phil.barnum@gmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Marion",
      nom: "Capriati",
      borne: 2,
      devis: null,
      etape: 3,
      contact: {
        adresse: "18 rue Tellier, 33000 Bordeaux",
        codePostal: 33000,
        tel: "01 23 45 67 89",
        email: "marion.cap@protonmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
    {
      prenom: "Kim",
      nom: "Kardash",
      borne: 2,
      devis: null,
      etape: 4,
      contact: {
        adresse: "1 rue Hollywood, 33100 Bordeaux",
        codePostal: 33100,
        tel: "01 23 45 67 89",
        email: "kim.kardash@gmail.com",
      },
      questionnaire: {
        residence: "Un appartement",
        parking: "À l'intérieur",
        status: "Propriétaire",
        notif: "Non",
        achat:
          "J'ai commandé mon véhicule électrique mais je ne l'ai pas encore",
        modele: "Mercedes EQS-SUV-500-4MATIC",
        usage: "Autoroute & ville",
        capacité: "118 kWh",
        delai: "3 mois",
        priseDeContact: "Oui",
        prix: null,
      },
    },
  ],
};

const clientsSlice = createSlice({
  name: "clients",
  initialState,
  reducers: {},
});

export default clientsSlice.reducer;
